////////////////////////////////////////////////////////////////////////////////
//! \file   Interfaces.idl
//! \brief  The COM interfaces.
//! \author Chris Oldwood

import "unknwn.idl";
import "oaidl.idl";

////////////////////////////////////////////////////////////////////////////////
//! The custom interface.

[
	object,
	uuid(CA3CA00E-182E-4ed1-A6B6-3F25451D118D),
	helpstring("The custom interface")
]
interface ICustomInterface : IUnknown
{
	HRESULT TestMethod([in] BSTR bstrInput, [out,retval] BSTR* pbstrOutput);
};

////////////////////////////////////////////////////////////////////////////////
//! The pure dispatch interface.

[
	uuid(2CB423B9-A460-4cb9-9737-239D75BB9A91),
	helpstring("The dispatch interface")
]
dispinterface IDispatchInterface
{
// Equivalent to "interface ICustomInterface"
	properties:
	methods:
	[id(1)] BSTR TestMethod(BSTR bstrInput);
};

////////////////////////////////////////////////////////////////////////////////
//! The dual custom/dispatch interface.

[
	dual,
	object,
	uuid(3EFF34FC-B3E5-4411-BD07-5187DFE54F98),
	helpstring("The dual custom/dispatch interface")
]
interface IDualInterface : IDispatch
{
	HRESULT TestMethod([in] BSTR bstrInput, [out,retval] BSTR* pbstrOutput);
};
