////////////////////////////////////////////////////////////////////////////////
//! \file   TypeLibrary.idl
//! \brief  The COM server type library.
//! \author Chris Oldwood

#include "Interfaces.idl"

[
	uuid(ABE74699-760D-4a59-9EED-CD269A81146D),
	helpstring("COMTrace Type Library"),
	version(1.0)
]
library COMTraceLib
{
	importlib("STDOLE2.TLB");

	//
	// Interfaces.
	//

	interface ICustomInterface;
	interface IDualInterface;


	//
	// Classes.
	//

	[
		uuid(F106F0CA-89C8-4729-AFDA-AFDD35F0BBAA),
		helpstring("The custom interface based Tracer class")
	]
	coclass CustomTracer
	{
		[default] interface ICustomInterface;
	};

	[
		uuid(3C061C1D-169D-4d18-8E7F-0E55445FDD69),
		helpstring("The dispatch interface based Tracer class")
	]
	coclass DispatchTracer
	{
		[default] dispinterface IDispatchInterface;
	};

	[
		uuid(A0FA298A-96F1-48d1-99DD-3E9CEC264C11),
		helpstring("The dual custom/dispatch interface based Tracer class")
	]
	coclass DualTracer
	{
		[default] interface IDualInterface;
	};
};
